### ISSUE TITLE
How to add path?

### ISSUE THREAD

**Issue by Henrietta1989** [halprin/man-viewer#1]
If i install stuff using MacPorts (PortAuthority) and HomeBrew (Cakebrew), what paths i should add to preferences "Man page directories so search"?

**Comment by halprin** [comment]
For Homebrew, I believe you'll want to just specify `/usr/local/share/man/` which is probably already there.  Homebrew doesn't install programs in non-standard locations.
I haven't used MacPorts for a while, but after a quick search, it seems `/opt/local/share/man/` should be the path you want

**Comment by Henrietta1989** [comment]
Thanks. I added both. But still i can't find man pages for these:

/opt/local/bin/afsctool
/usr/local/Cellar/mas/1.4.1/bin/mas

**Comment by halprin** [comment]
I would first ensure that `afsctool` and `mas` even have a man page.  Since they are command line programs, I would check `/usr/local/share/man/man1/` for something like `mas.1` and `/opt/local/share/man/man1/` for something like `afsctool.1`.

If those files do not exist, then either they do not have a man page or the package tool doesn't install it.  If those files do exist, then it may be a bug.
